//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seagulls
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattingScoreCard
    {
        public int MatchId { get; set; }
        public int PlayerId { get; set; }
        public int RunsScored { get; set; }
        public int BallsFaced { get; set; }
        public string HowOut { get; set; }
        public int NoOfFours { get; set; }
        public int NoOfSix { get; set; }
        public decimal StrikeRate { get; set; }
        public string LastupdatedBy { get; set; }
        public Nullable<System.DateTime> LastupdatedDate { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
