//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seagulls
{
    using System;
    using System.Collections.Generic;
    
    public partial class BowlingScoreCard
    {
        public int MatchId { get; set; }
        public int PlayerId { get; set; }
        public decimal Overs { get; set; }
        public int Runs { get; set; }
        public int Wickets { get; set; }
        public int Maidens { get; set; }
        public int Wides { get; set; }
        public int NoBalls { get; set; }
        public decimal RunPerOver { get; set; }
        public decimal StrikeRate { get; set; }
        public string LastupdatedBy { get; set; }
        public Nullable<System.DateTime> LastupdatedDate { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
