//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seagulls
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Match
    {
        public Match()
        {
            this.BattingScoreCards = new HashSet<BattingScoreCard>();
            this.BowlingScoreCards = new HashSet<BowlingScoreCard>();
        }
    
        public int Id { get; set; }
        public int LeagueId { get; set; }
             [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",
               ApplyFormatInEditMode = true)]
        public System.DateTime MatchDate { get; set; }
        public string Opponent { get; set; }
        public int VenuId { get; set; }
        public string Result { get; set; }
        public int TotalScore { get; set; }
        public int OpponentScore { get; set; }
        [Display(Name="Captain")]
        public int CaptainId { get; set; }
        [Display(Name = "Wicket Keeper")]
        public int WicketKeeperId { get; set; }
        public string ScoreSheetUrl { get; set; }
        public string LastupdatedBy { get; set; }
        public Nullable<System.DateTime> LastupdatedDate { get; set; }
    
        public virtual ICollection<BattingScoreCard> BattingScoreCards { get; set; }
        public virtual ICollection<BowlingScoreCard> BowlingScoreCards { get; set; }
        public virtual League League { get; set; }
        public virtual Venu Venu { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
