//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seagulls
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.BattingScoreCards = new HashSet<BattingScoreCard>();
            this.BowlingScoreCards = new HashSet<BowlingScoreCard>();
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int SkillId { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<BattingScoreCard> BattingScoreCards { get; set; }
        public virtual ICollection<BowlingScoreCard> BowlingScoreCards { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
    }
}
